### ISSUE TITLE
Uncaught TypeError: Cannot read property 'query' of undefined

### ISSUE THREAD

**Issue by gaurangkela** [strophe/strophejs-plugin-mam#8]
i want to get offline messages, and i have used mam for that but i'm getting error like
`Uncaught TypeError: Cannot read property 'query' of undefined` at connection.mam.query and `TypeError: connection.mam is undefined` sometimes, i have installed **strophejs-plugin-mam** and **strophejs-plugin-rsm** plugins but still the error is not resolved. my code which i have used is at below
```
connection.mam.query(Strophe.getBareJidFromJid(connection.jid), {
				"with": $scope.to_id, "before": '', "max": '',
				onMessage: function (message) {
	
					console.log("Message from ", $(message).find("forwarded message").attr("from"),
						": ", $(message).find("forwarded message body").text());
	
					return true;
	
				},
				onComplete: function (response) {
					console.log("Got all the messages");
	
				}
			});
```

**Comment by sualko** [comment]
Make sure to include those plugins after the strophe lib and that `Strophe` is available in global context.
